### ISSUE TITLE
Payment notification webhook not updating order

### ISSUE THREAD

**Issue by Taintedmedialtd** [Worldpay/worldpay-magento2#9]
Using Magento 2.1.5 and the latest version of this extension in Test mode. 
I can place an order, no problem, but the webhook doesn't update the order in the backend. This means no payment details reported back to the order in the admin panel and no order confirmation email is send. 
In the Magento backend the order says:
"Order # 000000054 (The order confirmation email is not sent)"
The webhook URL is correct and when testing it through the Worldpay admin panel it works with 200 OK as the response. 
When I visit the webhook URL it says [NOK] which might suggest Not OK but I can't find any documentation on that.
I've enabled the debugging mode and the transaction and response both seem to have worked properly. 
Any suggestions on how to finish off the order cycle so the order is updated and the email is issued? Or does it not finalise a Magento order in test mode?

**Comment by peterfich** [comment]
Hope I catch you before you are off for the long weekend.

I'm not sure what is going on here, Put I will get back to you as soon as I know more.


Peter

**Comment by Taintedmedialtd** [comment]
Thanks. Happy to provide you with any information you might need wrt to the local install.
If it helps, I'm guessing there's a breaking change been introduced in the 2.1.3 or .4 Magento updates to do with saving payment information.

**Comment by Taintedmedialtd** [comment]
After a bit more investigation I need to clarify the issue. The webhook does update the order with some basic information and to all intents works. It's only the order confirmation emails that aren't generated and sent out and the order shows as "The order confirmation email is not sent".
However, if you enable 3D secure everything works as expected. I noticed in one of your more recent commits a fix to send emails when 3DS is enabled and switching to that setting resolved the issue I was having.

**Comment by peterfich** [comment]
Just to be sure; does that mean that you have solved the problem?

**Comment by Taintedmedialtd** [comment]
I have a work-around I'm happy with but it might be worth looking in to.
